# Generated by Django 5.2.16 on 2026-07-22 15:29

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=160)),
                ('language', models.CharField(choices=[('de', 'Deutsch'), ('en', 'Englisch'), ('fr', 'Französisch'), ('es', 'Spanisch'), ('it', 'Italienisch'), ('tr', 'Türkisch'), ('ru', 'Russisch'), ('ar', 'Arabisch')], default='de', max_length=5)),
                ('level', models.CharField(blank=True, choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('color', models.CharField(choices=[('forest', 'Waldgrün'), ('gold', 'Gold'), ('blue', 'Blau'), ('berry', 'Beere'), ('slate', 'Schiefer')], default='forest', max_length=16)),
                ('provider', models.CharField(blank=True, max_length=40)),
                ('model', models.CharField(blank=True, max_length=80)),
                ('voice_id', models.CharField(blank=True, max_length=160)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speakers', to='projects.project')),
            ],
            options={
                'ordering': ('position', 'name'),
            },
        ),
        migrations.CreateModel(
            name='ScriptSegment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.PositiveIntegerField(default=0)),
                ('text', models.TextField(max_length=4000)),
                ('direction', models.CharField(blank=True, choices=[('', 'Keine'), ('friendly', 'freundlich'), ('cheerfully', 'erfreut'), ('surprised', 'überrascht'), ('whispering', 'flüsternd'), ('serious', 'ernst'), ('sad', 'traurig'), ('excited', 'aufgeregt'), ('hesitant', 'zögernd'), ('laughing', 'lachend')], max_length=24)),
                ('speed', models.DecimalField(decimal_places=2, default=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(1.5)])),
                ('pause_after_ms', models.PositiveIntegerField(default=500, validators=[django.core.validators.MaxValueValidator(5000)])),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='projects.project')),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='segments', to='projects.speaker')),
            ],
            options={
                'ordering': ('position', 'id'),
            },
        ),
    ]
