# Generated by Django 5.2.16 on 2026-07-22 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scriptsegment',
            name='speaker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='segments', to='projects.speaker'),
        ),
    ]
