# Generated by Django 5.2.16 on 2026-07-29 22:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_scriptsegment_speaker'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='demo_key',
            field=models.CharField(blank=True, editable=False, max_length=32),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(condition=models.Q(('demo_key', ''), _negated=True), fields=('owner', 'demo_key'), name='unique_owner_demo_project'),
        ),
    ]
