# Generated by Django 5.2.16 on 2026-08-06 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_demo_key_project_unique_owner_demo_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='accent',
            field=models.CharField(blank=True, choices=[('', 'Aus Grundstimme übernehmen'), ('british', 'Britisches Englisch'), ('american', 'Amerikanisches Englisch'), ('australian', 'Australisches Englisch'), ('irish', 'Irisches Englisch'), ('scottish', 'Schottisches Englisch'), ('indian_english', 'Indisches Englisch'), ('southern_us', 'Süd-USA')], max_length=24),
        ),
    ]
