# Generated by Django 5.2.16 on 2026-10-05 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_speaker_accent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scriptsegment',
            name='direction',
            field=models.CharField(blank=True, choices=[('', 'Normal'), ('friendly', 'freundlich'), ('cheerfully', 'erfreut'), ('surprised', 'überrascht'), ('whispering', 'flüsternd'), ('serious', 'ernst'), ('sad', 'traurig'), ('excited', 'aufgeregt'), ('hesitant', 'zögernd'), ('laughing', 'lachend')], max_length=24),
        ),
    ]
