# Generated by Django 5.2.16 on 2026-10-05 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_normal_direction_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='language',
            field=models.CharField(choices=[('de', 'Deutsch'), ('en', 'Englisch'), ('fr', 'Französisch'), ('es', 'Spanisch'), ('it', 'Italienisch'), ('tr', 'Türkisch'), ('ru', 'Russisch'), ('ar', 'Arabisch'), ('bg', 'Bulgarisch'), ('zh', 'Chinesisch'), ('da', 'Dänisch'), ('fi', 'Finnisch'), ('el', 'Griechisch'), ('hi', 'Hindi'), ('id', 'Indonesisch'), ('ja', 'Japanisch'), ('ko', 'Koreanisch'), ('hr', 'Kroatisch'), ('ms', 'Malaiisch'), ('nl', 'Niederländisch'), ('no', 'Norwegisch'), ('pl', 'Polnisch'), ('pt', 'Portugiesisch'), ('ro', 'Rumänisch'), ('sv', 'Schwedisch'), ('sk', 'Slowakisch'), ('fil', 'Filipino'), ('ta', 'Tamil'), ('cs', 'Tschechisch'), ('uk', 'Ukrainisch'), ('hu', 'Ungarisch'), ('vi', 'Vietnamesisch')], default='de', max_length=5),
        ),
    ]
