# Generated by Django 5.2.16 on 2026-10-01 12:26

import audio_studio.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('generation', '0003_usage_tracking'),
        ('projects', '0004_speaker_accent'),
        ('usage_control', '0002_alter_usageevent_feature'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudioConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Musik und Geräusche', max_length=80, verbose_name='Name')),
                ('music_enabled', models.BooleanField(default=False, verbose_name='Musikerzeugung freigeben')),
                ('effects_enabled', models.BooleanField(default=False, verbose_name='Geräuscherzeugung freigeben')),
                ('music_model', models.CharField(choices=[('music_v1', 'music_v1'), ('music_v2', 'music_v2'), ('music_v2_5', 'music_v2_5')], default='music_v1', max_length=80, verbose_name='Musikmodell')),
                ('music_eur_per_minute', models.DecimalField(decimal_places=4, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Musik: geschätzte EUR pro Minute')),
                ('effects_eur_per_minute', models.DecimalField(decimal_places=4, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Geräusche: geschätzte EUR pro Minute')),
                ('music_seconds_per_user_month', models.PositiveIntegerField(default=600, verbose_name='Musiksekunden je Benutzer und Monat')),
                ('effects_seconds_per_user_month', models.PositiveIntegerField(default=300, verbose_name='Geräuschsekunden je Benutzer und Monat')),
                ('encrypted_api_key', models.TextField(blank=True, editable=False)),
                ('api_key_hint', models.CharField(blank=True, editable=False, max_length=16)),
            ],
            options={
                'verbose_name': 'Musik- und Geräuschanbindung',
                'verbose_name_plural': 'Musik- und Geräuschanbindung',
            },
        ),
        migrations.CreateModel(
            name='StudioAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('speech', 'speech'), ('music', 'music'), ('effects', 'effects'), ('upload', 'upload'), ('mix', 'mix')], max_length=16)),
                ('file_path', models.CharField(max_length=500)),
                ('format', models.CharField(default='mp3', max_length=8)),
                ('duration', models.FloatField()),
                ('size_bytes', models.PositiveBigIntegerField()),
                ('waveform', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studio_assets', to='projects.project')),
                ('source_audio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='generation.audioasset')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='StudioJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('music', 'Musik'), ('effects', 'Geräusche'), ('export', 'Export')], max_length=16)),
                ('status', models.CharField(choices=[('queued', 'Wartet'), ('running', 'Wird verarbeitet'), ('succeeded', 'Fertig'), ('failed', 'Fehlgeschlagen')], default='queued', max_length=16)),
                ('input_data', models.JSONField()),
                ('duration', models.FloatField(default=0)),
                ('provider_request_id', models.CharField(blank=True, max_length=160)),
                ('provider_received', models.BooleanField(default=False)),
                ('error_message', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('asset', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='audio_studio.studioasset')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studio_jobs', to='projects.project')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('usage_event', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='usage_control.usageevent')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='StudioSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.PositiveIntegerField(default=0)),
                ('state', models.JSONField(default=audio_studio.models.empty_state)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='studio', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='StudioRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('state', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='audio_studio.studiosession')),
            ],
            options={
                'ordering': ('-number',),
                'constraints': [models.UniqueConstraint(fields=('session', 'number'), name='unique_studio_revision')],
            },
        ),
    ]
