# Generated by Django 5.2.16 on 2026-10-01 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_studio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studioasset',
            name='original_path',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
