# Generated by Django 5.2.16 on 2026-10-01 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_studio', '0002_studioasset_original_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='studiojob',
            name='provider_attempted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studiojob',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
