# Generated by Django 5.2.16 on 2026-10-01 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_studio', '0003_studiojob_provider_attempted_studiojob_started_at'),
        ('projects', '0004_speaker_accent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studioasset',
            name='is_demo_sample',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.CreateModel(
            name='StudioDemoEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.project')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='studio_demo_enrollment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
