# Generated by Django 5.2.16 on 2026-10-01 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_studio', '0004_studioasset_is_demo_sample_studiodemoenrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='studioconfiguration',
            name='effects_credits_per_second',
            field=models.PositiveIntegerField(default=20, verbose_name='Geräusche: geschätzte Credits pro Sekunde'),
        ),
        migrations.AddField(
            model_name='studioconfiguration',
            name='music_credits_per_minute',
            field=models.PositiveIntegerField(default=1500, verbose_name='Musik: geschätzte Credits pro Minute'),
        ),
        migrations.AlterField(
            model_name='studioconfiguration',
            name='effects_seconds_per_user_month',
            field=models.PositiveIntegerField(default=1800, verbose_name='Geräuschsekunden je Benutzer und Monat'),
        ),
        migrations.AlterField(
            model_name='studioconfiguration',
            name='music_seconds_per_user_month',
            field=models.PositiveIntegerField(default=1800, verbose_name='Musiksekunden je Benutzer und Monat'),
        ),
    ]
