# Generated by Django 5.2.16 on 2026-10-01 18:00

from django.db import migrations, models


def upgrade_music_model(apps, schema_editor):
    configuration = apps.get_model('audio_studio', 'StudioConfiguration')
    configuration.objects.using(schema_editor.connection.alias).filter(music_model__in=('music_v1', 'music_v2')).update(music_model='music_v2_5')


class Migration(migrations.Migration):

    dependencies = [
        ('audio_studio', '0005_studioconfiguration_effects_credits_per_second_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studioconfiguration',
            name='music_model',
            field=models.CharField(choices=[('music_v1', 'music_v1'), ('music_v2', 'music_v2'), ('music_v2_5', 'music_v2_5')], default='music_v2_5', max_length=80, verbose_name='Musikmodell'),
        ),
        migrations.RunPython(upgrade_music_model, migrations.RunPython.noop),
    ]
