# Generated by Django 5.2.16 on 2026-10-01 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_studio', '0006_alter_studioconfiguration_music_model'),
        ('projects', '0004_speaker_accent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studiojob',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='studio_jobs', to='projects.project'),
        ),
    ]
