# Generated by Django 5.2.16 on 2026-10-10 12:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def correct_standard_rate(apps, schema_editor):
    # Only replace the former default. Historical reservations keep their snapshot.
    apps.get_model('audio_studio', 'StudioConfiguration').objects.filter(effects_credits_per_second=20).update(effects_credits_per_second=40)


class Migration(migrations.Migration):

    dependencies = [
        ('audio_studio', '0007_alter_studiojob_project'),
        ('projects', '0006_expand_project_languages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studioasset',
            name='loopable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studioasset',
            name='source_duration',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='studioasset',
            name='variant_key',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='studioconfiguration',
            name='effects_credits_per_second',
            field=models.PositiveIntegerField(default=40, verbose_name='Geräusche: geschätzte Credits pro Sekunde'),
        ),
        migrations.RunPython(correct_standard_rate, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='studiojob',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='audio_studio.studioasset'),
        ),
        migrations.AlterField(
            model_name='studiojob',
            name='kind',
            field=models.CharField(choices=[('music', 'Musik'), ('effects', 'Geräusche'), ('export', 'Export'), ('library_prepare', 'Bibliothek vorbereiten')], max_length=16),
        ),
        migrations.CreateModel(
            name='SoundLibraryAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.SlugField(max_length=80, verbose_name='Bibliotheksschlüssel')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Version')),
                ('title', models.CharField(max_length=120, verbose_name='Name')),
                ('description', models.CharField(max_length=500, verbose_name='Beschreibung')),
                ('category', models.CharField(choices=[('school', 'Schule & Alltag'), ('city', 'Stadt & Verkehr'), ('nature', 'Natur & Wetter'), ('indoors', 'Innenräume & Begegnung'), ('actions', 'Bewegung & Gegenstände')], max_length=16, verbose_name='Kategorie')),
                ('role', models.CharField(choices=[('atmosphere', 'Atmosphäre'), ('oneshot', 'Einzelgeräusch')], max_length=16, verbose_name='Verwendung')),
                ('tags', models.CharField(blank=True, max_length=500, verbose_name='Suchbegriffe / Synonyme')),
                ('status', models.CharField(choices=[('draft', 'Entwurf'), ('published', 'Freigegeben'), ('retired', 'Zurückgezogen')], default='draft', max_length=16, verbose_name='Status')),
                ('master_path', models.CharField(blank=True, editable=False, max_length=500)),
                ('file_path', models.CharField(blank=True, editable=False, max_length=500)),
                ('preview_path', models.CharField(blank=True, editable=False, max_length=500)),
                ('duration', models.FloatField(default=0, editable=False)),
                ('source_duration', models.FloatField(default=0, editable=False)),
                ('waveform', models.JSONField(default=list, editable=False)),
                ('loop_verified', models.BooleanField(default=False, verbose_name='Wiederholung akustisch geprüft')),
                ('gain_db', models.FloatField(default=-20, verbose_name='Empfohlener Clippegel (dB)')),
                ('fade_in', models.FloatField(default=1, verbose_name='Einblenden (s)')),
                ('fade_out', models.FloatField(default=2, verbose_name='Ausblenden (s)')),
                ('provenance', models.CharField(blank=True, max_length=500, verbose_name='Herkunft / Nutzungsfreigabe')),
                ('generation_prompt', models.TextField(blank=True, verbose_name='Erzeugungsbeschreibung')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Bibliotheksgeräusch',
                'verbose_name_plural': 'Geräuschbibliothek',
                'ordering': ('category', 'title', '-version'),
                'constraints': [models.UniqueConstraint(fields=('key', 'version'), name='unique_library_version')],
            },
        ),
        migrations.AddField(
            model_name='studioasset',
            name='library_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='audio_studio.soundlibraryasset'),
        ),
        migrations.CreateModel(
            name='SoundLibraryRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('used', 'Verwendet'), ('missing', 'Fehlender Wunsch'), ('suggestion', 'Zur Prüfung vorgeschlagen')], max_length=16, verbose_name='Art')),
                ('label', models.CharField(max_length=120, verbose_name='Geräuschwunsch')),
                ('key', models.CharField(max_length=140)),
                ('status', models.CharField(choices=[('open', 'Offen'), ('reviewed', 'Geprüft')], default='open', max_length=16, verbose_name='Bearbeitungsstand')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='audio_studio.studioasset')),
                ('library_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='audio_studio.soundlibraryasset')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.project')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Geräuschbedarf / Vorschlag',
                'verbose_name_plural': 'Geräuschbedarf und Vorschläge',
                'ordering': ('-created_at',),
                'constraints': [models.UniqueConstraint(fields=('project', 'kind', 'key'), name='unique_sound_demand_project')],
            },
        ),
    ]
