# Generated by Django 5.2.16 on 2026-07-22 15:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('snapshot', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_versions', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='projects.project')),
            ],
            options={
                'ordering': ('-number',),
            },
        ),
        migrations.CreateModel(
            name='GenerationJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('queued', 'Wartet'), ('running', 'Wird erzeugt'), ('succeeded', 'Fertig'), ('failed', 'Fehlgeschlagen'), ('cancelled', 'Abgebrochen')], default='queued', max_length=16)),
                ('provider', models.CharField(max_length=40)),
                ('model', models.CharField(max_length=80)),
                ('character_count', models.PositiveIntegerField()),
                ('estimated_cost_eur', models.DecimalField(decimal_places=4, max_digits=10)),
                ('actual_cost_eur', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('provider_request_ids', models.JSONField(default=list)),
                ('error_message', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generation_jobs', to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='generation.projectversion')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AudioAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_path', models.CharField(max_length=500)),
                ('format', models.CharField(default='mp3', max_length=16)),
                ('duration_seconds', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('size_bytes', models.PositiveBigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='audio_asset', to='generation.generationjob')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_assets', to='generation.projectversion')),
            ],
        ),
        migrations.CreateModel(
            name='UsageLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=40)),
                ('model', models.CharField(max_length=80)),
                ('character_count', models.PositiveIntegerField()),
                ('estimated_cost_eur', models.DecimalField(decimal_places=4, max_digits=10)),
                ('actual_cost_eur', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('billing_period', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='usage_entry', to='generation.generationjob')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usage_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='GenerationPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Wartet'), ('running', 'Wird erzeugt'), ('succeeded', 'Fertig'), ('failed', 'Fehlgeschlagen')], default='pending', max_length=16)),
                ('input_data', models.JSONField()),
                ('character_count', models.PositiveIntegerField()),
                ('pause_after_ms', models.PositiveIntegerField(default=0)),
                ('audio_path', models.CharField(blank=True, max_length=500)),
                ('provider_request_id', models.CharField(blank=True, max_length=160)),
                ('error_message', models.CharField(blank=True, max_length=500)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='generation.generationjob')),
            ],
            options={
                'ordering': ('position',),
                'constraints': [models.UniqueConstraint(fields=('job', 'position'), name='unique_generation_part_position')],
            },
        ),
        migrations.AddConstraint(
            model_name='projectversion',
            constraint=models.UniqueConstraint(fields=('project', 'number'), name='unique_project_version_number'),
        ),
    ]
