# Generated by Django 5.2.16 on 2026-10-01 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generation', '0003_usage_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationjob',
            name='is_copy',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='generationjob',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='generation.projectversion'),
        ),
    ]
