# Generated by Django 5.2.16 on 2026-10-01 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generation', '0004_generationjob_is_copy_alter_generationjob_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationpart',
            name='is_reused',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='generationpart',
            name='playback_speed',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=3),
        ),
        migrations.AddField(
            model_name='generationpart',
            name='reuse_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reused_parts', to='generation.generationpart'),
        ),
    ]
