"""The initial, deliberately language-neutral catalogue; no provider credentials."""
STARTER_SOUNDS = [
    dict(key="pausenhof", title="Pausenhof", category="school", role="atmosphere", tags="Schulhof Pause Schule Kinder Jugendliche playground schoolyard", description="Entfernte Pausenhofkulisse mit Bewegung und unverständlichen Stimmen.", seconds=30, prompt="Seamless ambient school playground soundscape at a distance, gentle indistinct children and teenagers crowd murmur, footsteps and outdoor activity. No intelligible words, no close voices, no bells, no music, no loud shouting. Steady natural background suitable underneath spoken dialogue."),
    dict(key="strasse", title="Straße", category="city", role="atmosphere", tags="Verkehr Stadt Straße Autos street traffic", description="Mäßiger Straßenverkehr und entfernte Schritte.", seconds=30, prompt="Seamless ambient moderately busy urban street, soft distant passing cars and occasional subtle footsteps. Consistent neutral background, no horns, no sirens, no intelligible speech, no music, no dramatic events, suitable underneath spoken dialogue."),
    dict(key="marktplatz", title="Marktplatz", category="city", role="atmosphere", tags="Markt Menschen Platz market square crowd", description="Belebtes Murmeln auf einem offenen Marktplatz.", seconds=30, prompt="Seamless ambient open air market square, gentle diffuse crowd murmur and distant pedestrian movement. Natural steady background, absolutely no intelligible words or vendor calls, no music, no horns, no loud foreground events, suitable underneath spoken dialogue."),
    dict(key="wald", title="Wald am Tag", category="nature", role="atmosphere", tags="Wald Bäume Vögel Blätter forest woods birds", description="Ruhige Waldkulisse mit Blätterrauschen und verstreuten Vögeln.", seconds=30, prompt="Seamless calm daytime forest ambience, gentle rustling leaves and sparse soft distant birdsong. Steady natural background, no footsteps, no voices, no music, no strong repeating bird motif, no dramatic events, suitable underneath spoken dialogue."),
    dict(key="sommernacht", title="Sommernacht", category="nature", role="atmosphere", tags="Nacht Sommer Grillen Insekten summer night crickets", description="Dezente Insekten und eine ruhige nächtliche Außenatmosphäre.", seconds=30, prompt="Seamless quiet summer night ambience outdoors, soft diffuse crickets and subtle insects, gentle distant night air. Natural steady low intensity background, no loud animal cries, no voices, no music, no dramatic events, suitable underneath spoken dialogue."),
    dict(key="wind", title="Wind in den Bäumen", category="nature", role="atmosphere", tags="Wind Bäume Wetter Blätter wind breeze", description="Sanfter Wind mit leichtem Rauschen in den Bäumen.", seconds=30, prompt="Seamless gentle wind moving through leafy trees, soft steady breeze with subtle natural variation. No storm, no microphone distortion, no voices, no music, no birds or other prominent events, suitable underneath spoken dialogue."),
    dict(key="cafe", title="Café", category="indoors", role="atmosphere", tags="Cafe Café Kaffee Restaurant coffee cafe", description="Gedämpftes Stimmengewirr mit gelegentlichem Geschirr.", seconds=30, prompt="Seamless small cafe interior ambience, quiet diffuse indistinct adult crowd murmur, occasional very soft cups and crockery. No intelligible words, no close conversation, no music, no loud machine sounds, steady background suitable underneath spoken dialogue."),
    dict(key="bahnhof", title="Bahnhof / Bahnsteig", category="city", role="atmosphere", tags="Bahnhof Zug Bahnsteig Station train railway", description="Entfernte Zug- und Menschenkulisse ohne Durchsagen.", seconds=30, prompt="Seamless quiet railway platform ambience, soft distant stationary train hum and gentle diffuse pedestrian movement. No announcements, no intelligible speech, no whistles, no loud arrival or departure event, no music, steady background suitable underneath spoken dialogue."),
    dict(key="tuer-auf", title="Tür öffnen", category="actions", role="oneshot", tags="Tür auf öffnen door open", description="Eine gewöhnliche Tür wird einmal geöffnet.", seconds=3, prompt="One ordinary wooden interior door opening, handle clicks softly then a brief natural hinge sound. Single event with clean beginning and complete tail, no voices, no music, no background ambience."),
    dict(key="tuer-zu", title="Tür schließen", category="actions", role="oneshot", tags="Tür zu schließen door close", description="Eine gewöhnliche Tür wird einmal geschlossen.", seconds=3, prompt="One ordinary interior door closing gently with a clear latch click. Single natural event with complete tail, not slammed, no voices, no music, no background ambience."),
    dict(key="klopfen", title="Klopfen", category="actions", role="oneshot", tags="Klopfen Tür knocking knock", description="Drei kurze Klopfzeichen an einer Tür.", seconds=3, prompt="Three clear gentle knocks on an ordinary wooden door, one short sequence with clean tail, no opening door, no voices, no music, no background ambience."),
    dict(key="schritte-gehweg", title="Schritte auf Gehweg", category="actions", role="oneshot", tags="Schritte Laufen Gehen Straße footsteps pavement", description="Eine kurze Folge ruhiger Schritte auf festem Boden.", seconds=6, prompt="A short natural sequence of one person walking calmly on a pavement in ordinary shoes. Clear isolated footsteps, no running, no voices, no music, no other background sounds."),
    dict(key="schritte-kies", title="Schritte auf Kies", category="actions", role="oneshot", tags="Schritte Kies Weg Garten footsteps gravel", description="Eine kurze Folge knirschender Schritte auf Kies.", seconds=6, prompt="A short natural sequence of one person walking calmly on fine gravel, subtle crunching footsteps. Clear isolated footsteps, no voices, no music, no other background sounds."),
    dict(key="handy", title="Handyklingeln", category="actions", role="oneshot", tags="Handy Telefon Klingeln phone ring", description="Ein kurzer, neutraler Telefonklingelton.", seconds=4, prompt="A short simple generic mobile phone ringing alert, clean neutral electronic tones. Original unbranded ringtone, no familiar melody, no voices, no music, no background ambience."),
    dict(key="schulglocke", title="Schulglocke", category="school", role="oneshot", tags="Schule Glocke Pause Klingel school bell", description="Ein kurzer Gong kündigt die Schulpause an.", seconds=3, prompt="One short ordinary school bell chime announcing a break, clear soft electronic school gong with natural complete decay, no crowd, no voices, no music."),
    dict(key="vogel", title="Einzelner Vogelruf", category="nature", role="oneshot", tags="Vogel Ruf Zwitschern bird call chirp", description="Ein kurzer natürlicher Vogelruf.", seconds=3, prompt="A single small songbird making one short natural chirping phrase outdoors. Isolated clean bird call with complete tail, no flock, no wind, no voices, no music."),
]
