# Generated by Django 5.2.16 on 2026-10-01 21:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audio_studio', '0007_alter_studiojob_project'),
        ('generation', '0005_generationpart_is_reused_and_more'),
        ('projects', '0004_speaker_accent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('script', 'Skript prüfen'), ('speech', 'Hörtext prüfen'), ('plan', 'Klanggestaltung planen'), ('mix', 'Mischung prüfen'), ('complete', 'Fertiges Hörspiel')], default='script', max_length=16)),
                ('revision', models.PositiveIntegerField(default=0)),
                ('brief', models.JSONField(default=dict)),
                ('draft', models.JSONField(default=dict)),
                ('approved_script', models.JSONField(default=dict)),
                ('plan', models.JSONField(default=dict)),
                ('materials', models.JSONField(default=dict)),
                ('mixed_revision', models.PositiveIntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_audio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='generation.audioasset')),
                ('final_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_finals', to='audio_studio.studioasset')),
                ('mix_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_previews', to='audio_studio.studioasset')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='production', to='projects.project')),
                ('speech_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='generation.generationjob')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('script', 'Skript entwerfen'), ('refine', 'Skript überarbeiten'), ('speech', 'Hörtext erzeugen'), ('plan', 'Klangplan entwerfen'), ('mix', 'Mischung erstellen'), ('preview', 'Studioschnitt anhören'), ('export', 'Hörspiel exportieren')], max_length=20)),
                ('status', models.CharField(choices=[('queued', 'Wartet'), ('running', 'In Arbeit'), ('succeeded', 'Fertig'), ('failed', 'Fehlgeschlagen')], default='queued', max_length=16)),
                ('input_data', models.JSONField(default=dict)),
                ('result', models.JSONField(default=dict)),
                ('error_message', models.CharField(blank=True, max_length=500)),
                ('progress', models.CharField(blank=True, max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_runs', to='projects.project')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['queued', 'running'])), fields=('project',), name='one_active_production_run')],
            },
        ),
    ]
