# Generated by Django 5.2.16 on 2026-07-29 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='demo_projects_initialized',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
