# Generated by Django 5.2.16 on 2026-10-01 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_temporary_student_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='character_limit',
            field=models.PositiveIntegerField(default=100000),
        ),
        migrations.AlterField(
            model_name='user',
            name='openai_daily_request_limit',
            field=models.PositiveIntegerField(default=100, verbose_name='OpenAI-Anfragen pro Tag'),
        ),
        migrations.AlterField(
            model_name='user',
            name='openai_monthly_input_token_limit',
            field=models.PositiveIntegerField(default=2000000, verbose_name='OpenAI-Eingabetokens pro Monat'),
        ),
        migrations.AlterField(
            model_name='user',
            name='openai_monthly_output_token_limit',
            field=models.PositiveIntegerField(default=500000, verbose_name='OpenAI-Ausgabetokens pro Monat'),
        ),
    ]
