# Generated by Django 5.2.16 on 2026-10-01 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usage_control', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usageevent',
            name='feature',
            field=models.CharField(choices=[('audio', 'Audioerzeugung'), ('music', 'Musikerzeugung'), ('sound_effects', 'Geräuscherzeugung'), ('script_assistant', 'KI-Hörtextassistent')], max_length=40),
        ),
    ]
