# Generated by Django 5.2.16 on 2026-10-01 17:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usage_control', '0002_alter_usageevent_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerbudget',
            name='credit_cycle_day',
            field=models.PositiveSmallIntegerField(default=0, help_text='0 verwendet vorsichtig die letzten 31 Tage. Sonst: Tag im Monat laut Anbieter-Abonnement; kurze Monate verwenden ihren letzten Tag.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(31)], verbose_name='Erneuerungstag der Credits'),
        ),
        migrations.AddField(
            model_name='providerbudget',
            name='monthly_credit_limit',
            field=models.PositiveIntegerField(default=0, help_text='0 verwendet das Geldbudget. Ein positiver Wert ersetzt es durch einen gemeinsamen Credit-Rahmen für Sprache, Musik und Geräusche; zählt nur Plattformnutzung.', verbose_name='ElevenLabs-Credits je Abrechnungszyklus'),
        ),
        migrations.AddField(
            model_name='usageevent',
            name='estimated_credits',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
    ]
