# Generated by Django 5.2.16 on 2026-10-05 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usage_control', '0003_providerbudget_credit_cycle_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usageevent',
            name='feature',
            field=models.CharField(choices=[('audio', 'Audioerzeugung'), ('music', 'Musikerzeugung'), ('sound_effects', 'Geräuscherzeugung'), ('script_assistant', 'KI-Hörtextassistent'), ('worksheet', 'Arbeitsblatt-Assistent')], max_length=40),
        ),
    ]
