# Generated by Django 5.2.16 on 2026-10-05 21:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0006_expand_project_languages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Worksheet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('queued', 'Wird vorbereitet'), ('running', 'Wird erstellt'), ('ready', 'Entwurf zur Prüfung'), ('failed', 'Nicht abgeschlossen')], default='queued', max_length=12)),
                ('brief', models.JSONField(default=dict)),
                ('source', models.JSONField(default=dict)),
                ('payload', models.JSONField(default=dict)),
                ('error_message', models.CharField(blank=True, max_length=500)),
                ('revision', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worksheets', to='projects.project')),
            ],
            options={
                'verbose_name': 'Arbeitsblatt',
                'verbose_name_plural': 'Arbeitsblätter',
                'ordering': ('-created_at',),
            },
        ),
    ]
