# Generated by Django 5.2.16 on 2026-07-22 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderVoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=40)),
                ('model', models.CharField(max_length=80)),
                ('voice_id', models.CharField(max_length=160)),
                ('display_name', models.CharField(max_length=120)),
                ('languages', models.JSONField(default=list)),
                ('labels', models.JSONField(blank=True, default=dict)),
                ('preview_url', models.URLField(blank=True, max_length=500)),
                ('active', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('display_name',),
                'constraints': [models.UniqueConstraint(fields=('provider', 'model', 'voice_id'), name='unique_provider_model_voice')],
            },
        ),
    ]
