# Generated by Django 5.2.16 on 2026-10-01 18:00

from django.db import migrations, models


def upgrade_speech_model(apps, schema_editor):
    database = schema_editor.connection.alias
    configuration = apps.get_model('tts', 'TTSConfiguration')
    voice = apps.get_model('tts', 'ProviderVoice')
    favorite = apps.get_model('tts', 'VoiceFavorite')
    speaker = apps.get_model('projects', 'Speaker')
    # Voice IDs remain compatible. Preserve local PKs, curation and favorites.
    for old in voice.objects.using(database).filter(provider='elevenlabs', model='eleven_v3').iterator():
        target = voice.objects.using(database).filter(provider=old.provider, model='eleven_v4', voice_id=old.voice_id).first()
        if target:
            labels = {**old.labels, **target.labels}
            for key in ('curated_matches',):
                if key in old.labels or key in target.labels:
                    labels[key] = sorted(set(old.labels.get(key, [])) | set(target.labels.get(key, [])))
            if 'curated_ranks' in old.labels or 'curated_ranks' in target.labels:
                labels['curated_ranks'] = {**old.labels.get('curated_ranks', {}), **target.labels.get('curated_ranks', {})}
            voice.objects.using(database).filter(pk=target.pk).update(
                active=old.active or target.active, labels=labels,
                languages=sorted(set(old.languages) | set(target.languages)))
            for item in favorite.objects.using(database).filter(voice_id=old.pk):
                favorite.objects.using(database).get_or_create(user_id=item.user_id, voice_id=target.pk)
            old.delete(using=database)
        else:
            voice.objects.using(database).filter(pk=old.pk).update(model='eleven_v4')
    speaker.objects.using(database).filter(provider='elevenlabs', model='eleven_v3').update(model='eleven_v4')
    configuration.objects.using(database).filter(model='eleven_v3').update(model='eleven_v4')
    # Saved generation snapshots, jobs and usage history keep their original model.


class Migration(migrations.Migration):

    dependencies = [
        ('tts', '0003_ttsconfiguration'),
        ('projects', '0004_speaker_accent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ttsconfiguration',
            name='model',
            field=models.CharField(choices=[('eleven_v4', 'Eleven v4 · empfohlen'), ('eleven_v3', 'Eleven v3 · vorherige Version')], default='eleven_v4', max_length=80),
        ),
        migrations.RunPython(upgrade_speech_model, migrations.RunPython.noop),
    ]
