# Generated by Django 5.2.16 on 2026-07-22 15:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantProposal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payload', models.JSONField()),
                ('status', models.CharField(choices=[('pending', 'Zur Prüfung'), ('applied', 'Übernommen'), ('discarded', 'Verworfen'), ('reverted', 'Rückgängig gemacht')], default='pending', max_length=16)),
                ('apply_mode', models.CharField(blank=True, choices=[('replace', 'Skript ersetzen'), ('append', 'Skript ergänzen')], max_length=16)),
                ('previous_snapshot', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assistant_proposals', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_proposals', to='projects.project')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
