# Generated by Django 5.2.16 on 2026-07-22 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('script_assistant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistantproposal',
            name='applied_snapshot',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
