# Generated by Django 5.2.16 on 2026-10-01 18:00

from django.db import migrations, models


def upgrade_quality_model(apps, schema_editor):
    configuration = apps.get_model('script_assistant', 'AssistantConfiguration')
    rows = configuration.objects.using(schema_editor.connection.alias).filter(model='gpt-6-sol')
    rows.filter(reasoning_effort='none').update(reasoning_effort='low')
    # Standard input/output prices are unchanged; preserve custom pricing.
    rows.update(model='gpt-6.1-sol')


class Migration(migrations.Migration):

    dependencies = [
        ('script_assistant', '0005_gpt6_models_and_reasoning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistantconfiguration',
            name='model',
            field=models.CharField(choices=[('gpt-6-luna', 'GPT-6 Luna · sparsam'), ('gpt-6.1-sol', 'GPT-6.1 Sol · höhere Qualität'), ('gpt-6-sol', 'GPT-6 Sol · vorherige Version')], default='gpt-6-luna', max_length=80),
        ),
        migrations.AlterField(
            model_name='assistantconfiguration',
            name='reasoning_effort',
            field=models.CharField(choices=[('none', 'Ohne zusätzlichen Reasoning-Aufwand'), ('low', 'Niedrig · empfohlen'), ('medium', 'Mittel'), ('high', 'Hoch')], default='low', help_text='Niedrig genügt normalerweise für Hörtexte. GPT-6.1 Sol benötigt mindestens Niedrig.', max_length=16, verbose_name='Reasoning-Aufwand'),
        ),
        migrations.RunPython(upgrade_quality_model, migrations.RunPython.noop),
    ]
